on:
  push:
    branches:
      - 'release/**'
jobs:
  deployment:
    name: "Build production deployment"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run buildProd --if-present
      - run: npm run pack --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: addon
          path: "*.tar"
      - name: Extract branch name
        id: extract_version
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          VERSION=${BRANCH_NAME##*/}
          echo "Full branch name: $BRANCH_NAME"
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.extract_version.outputs.version }}"
          prerelease: false
          title: "Release"
          files: |
            LICENCE.md
            *.tar
          
